-- --------------------------------------------------------
-- Host:                         carbonuat.cxivby4riwed.us-east-1.rds.amazonaws.com
-- Server version:               5.6.23-log - MySQL Community Server (GPL)
-- Server OS:                    Linux
-- HeidiSQL Version:             8.0.0.4396
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dumping structure for table wg_mscripts.device_staging_histories
DROP TABLE IF EXISTS `device_staging_histories`;
CREATE TABLE IF NOT EXISTS `device_staging_histories` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK of the table',
  `client_id` int(10) unsigned NOT NULL COMMENT 'FK to the clients table',
  `device_staging_id` int(10) unsigned NOT NULL COMMENT 'ID of the device_stagings record',
  `international_code` varchar(10) DEFAULT '1' COMMENT 'International code of the user mobile number',
  `mobile_number` varchar(25) DEFAULT NULL COMMENT 'The user mobile number',
  `enable_prefix` char(1) NOT NULL DEFAULT '0' COMMENT 'Enable prefix flag',
  `created_at` datetime NOT NULL COMMENT 'This field specifies the  date and time when the record was created',
  `created_by` varchar(45) NOT NULL COMMENT 'ID of the user who created this record',
  `updated_at` datetime NOT NULL COMMENT 'This field specifies the  date and time when the record was created or updated',
  `last_updated_by` varchar(45) NOT NULL COMMENT 'ID of the user who created or last updated this record',
  `verification_code` varchar(10) DEFAULT NULL COMMENT 'Verification code associated with the user signup process',
  `primary_store_id` varchar(45) DEFAULT NULL COMMENT 'Primary store id selected by the user during signup process',
  `timezone` varchar(100) DEFAULT NULL COMMENT 'Timezone selected by the user during signup process',
  `sms_token` varchar(100) DEFAULT NULL COMMENT 'Sms Token generated by PDX for user signup',
  `signup_mode` varchar(45) DEFAULT NULL COMMENT 'Mode of signup - onphone/store',
  `device_id` int(10) unsigned DEFAULT NULL COMMENT 'FK to the devices table - for phone number updates',
  `first_name` varchar(48) DEFAULT NULL COMMENT 'First Name of the user',
  `last_name` varchar(48) DEFAULT NULL COMMENT 'Last Name of the user',
  `session_id` varchar(100) DEFAULT NULL COMMENT 'The mscripts session ID which is generated when the user logs into the application',
  `web_logic_session_id` varchar(200) DEFAULT NULL COMMENT 'The PDX web logic session ID which is generated when the user logs into the application',
  `primary_store_alias` varchar(200) DEFAULT NULL COMMENT 'Primary store alias selected by the user during signup process',
  `action_log_id` int(10) unsigned DEFAULT NULL COMMENT 'FK to the action_logs table',
  `customer_username` varchar(32) DEFAULT NULL COMMENT 'The PDX username',
  `shortcode` varchar(10) DEFAULT NULL COMMENT 'Shortcode assigned to this user',
  `shortcode_username` varchar(45) DEFAULT NULL COMMENT 'Username for shortcode',
  `shortcode_serviceid` varchar(20) DEFAULT NULL COMMENT 'mblox shortcode serviceid',
  `is_mobile_access_number` char(1) DEFAULT NULL COMMENT 'Flag that defines a proxy signup user',
  `email_address` varchar(256) DEFAULT NULL COMMENT 'Primary email address for user assigned from PDX',
  `customer_dob` varchar(16) DEFAULT NULL COMMENT 'Date of Birth for user assigned from PDX',
  `patient_id` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `i_action_log_id` (`action_log_id`),
  KEY `i_client_id` (`client_id`),
  KEY `i_customer_dob` (`customer_dob`),
  KEY `i_customer_username` (`customer_username`),
  KEY `i_device_id` (`device_id`),
  KEY `i_device_staging_id` (`device_staging_id`),
  KEY `i_email_address` (`email_address`),
  KEY `i_first_name` (`first_name`),
  KEY `i_int_code_mob_num_verf_code` (`international_code`,`mobile_number`,`verification_code`),
  KEY `i_last_name` (`last_name`),
  KEY `i_sms_token` (`sms_token`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Updated/Deleted device staging records';

-- Data exporting was unselected.
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
