-- --------------------------------------------------------
-- Host:                         carbonuat.cxivby4riwed.us-east-1.rds.amazonaws.com
-- Server version:               5.6.23-log - MySQL Community Server (GPL)
-- Server OS:                    Linux
-- HeidiSQL Version:             8.0.0.4396
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dumping structure for table wg_mscripts.mblox_audit_log_histories
DROP TABLE IF EXISTS `mblox_audit_log_histories`;
CREATE TABLE IF NOT EXISTS `mblox_audit_log_histories` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK of the table',
  `client_id` int(10) unsigned NOT NULL COMMENT 'FK to the clients table',
  `mblox_audit_logs_id` int(10) DEFAULT NULL COMMENT 'The id of record in mblox_audit_logs table',
  `batch_id` varchar(45) NOT NULL COMMENT 'Batch id of the message generated by mscripts',
  `subscriber_number` varchar(45) NOT NULL COMMENT 'Subscriber number',
  `status` varchar(100) NOT NULL COMMENT 'mblox message status',
  `timestamp` varchar(100) NOT NULL COMMENT 'Timestamp when the message was actually delivered to the user handset',
  `msg_reference` varchar(100) NOT NULL COMMENT 'mblox message reference value',
  `reason` varchar(500) NOT NULL COMMENT 'Stores the value of "reason" node',
  `created_at` datetime NOT NULL COMMENT 'This field specifies the  date and time when the record was created',
  `created_by` varchar(45) NOT NULL COMMENT 'ID of the user who created this record',
  `updated_at` varchar(45) NOT NULL COMMENT 'This field specifies the  date and time when the record was created or updated',
  `last_updated_by` varchar(45) NOT NULL COMMENT 'ID of the user who created or last updated this record',
  `update_error` varchar(200) DEFAULT NULL COMMENT 'Field to track errors',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='mblox notification service logs histories';

-- Data exporting was unselected.
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
